version: '3'
services:

   node1:
     image: anierbeck/karaf-vertx-cluster-docker:0.1

   node2:
     image: anierbeck/karaf-vertx-cluster-docker:0.1

   node3:
     image: anierbeck/karaf-vertx-cluster-docker:0.1

   haproxy:
     image: hypriot/rpi-haproxy
     links:
       - node1
       - node2
       - node3
     ports:
       - "8080:8080"
       - "70:70"
     expose:
      - "8080"
      - "70"